# Titanic Survival Prediction using Machine Learning

### Week 2 - First ML Model

**Dataset:** Titanic Dataset

**Objective:**
The objective of this project is to predict whether a passenger survived or not using Machine Learning algorithms.

## Step 1: Import Required Libraries

In [46]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

## Step 2: Load the Dataset

In [25]:
df = pd.read_csv(r"C:\Users\Kishore\Downloads\titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

## Step 3: Explore the Dataset

In [26]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [27]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [28]:
df['Sex'].head()

0      male
1    female
2    female
3    female
4      male
Name: Sex, dtype: object

## Step 4: Data Preprocessing

In [32]:
df = df[['Survived','Pclass','Sex','Age','Fare']].copy()

In [34]:
df['Age'] = df['Age'].fillna(df['Age'].median())
df

     Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
888         0       3  female  28.0  23.4500
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[891 rows x 5 columns]

In [35]:
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})
df

     Survived  Pclass  Sex   Age     Fare
0           0       3    0  22.0   7.2500
1           1       1    1  38.0  71.2833
2           1       3    1  26.0   7.9250
3           1       1    1  35.0  53.1000
4           0       3    0  35.0   8.0500
..        ...     ...  ...   ...      ...
886         0       2    0  27.0  13.0000
887         1       1    1  19.0  30.0000
888         0       3    1  28.0  23.4500
889         1       1    0  26.0  30.0000
890         0       3    0  32.0   7.7500

[891 rows x 5 columns]

In [36]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
Fare        0
dtype: int64

## Step 5: Prepare Features and Target Variable

In [37]:
X = df[['Pclass', 'Sex', 'Age', 'Fare']]
y = df['Survived']

## Step 6: Split Dataset into Training and Testing Sets

In [38]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

## Step 7: Train Logistic Regression Model

In [39]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

pred_lr = lr.predict(X_test)

In [40]:
from sklearn.metrics import accuracy_score

print("Logistic Regression Accuracy:", accuracy_score(y_test, pred_lr))

Logistic Regression Accuracy: 0.8044692737430168

In [41]:
from sklearn.metrics import classification_report

print(classification_report(y_test, pred_lr))

              precision    recall  f1-score   support

           0       0.82      0.86      0.84       105
           1       0.78      0.73      0.76        74

    accuracy                           0.80       179
   macro avg       0.80      0.79      0.80       179
weighted avg       0.80      0.80      0.80       179

## Step 8: Train Decision Tree Model

In [42]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train, y_train)

pred_dt = dt.predict(X_test)

In [43]:
print("Decision Tree Accuracy:", accuracy_score(y_test, pred_dt))

Decision Tree Accuracy: 0.7318435754189944

In [44]:
print(classification_report(y_test, pred_dt))

              precision    recall  f1-score   support

           0       0.79      0.74      0.76       105
           1       0.66      0.72      0.69        74

    accuracy                           0.73       179
   macro avg       0.73      0.73      0.73       179
weighted avg       0.74      0.73      0.73       179

## Step 9: Compare Model Performance

In [45]:
print("Logistic Regression Accuracy :", accuracy_score(y_test, pred_lr))
print("Decision Tree Accuracy       :", accuracy_score(y_test, pred_dt))

Logistic Regression Accuracy : 0.8044692737430168
Decision Tree Accuracy       : 0.7318435754189944

# Final Conclusion

- The Titanic dataset was successfully preprocessed and used for machine learning classification.
- Two models, Logistic Regression and Decision Tree, were trained and evaluated.
- Logistic Regression achieved an accuracy of **80.44%**.
- The better-performing model was selected based on accuracy.
- This project demonstrates a complete machine learning workflow using Scikit-learn.